AllCops:
  Exclude:
    - rails-formation.gemspec
    - spec/templates/*
  DisplayCopNames: true
  NewCops: enable
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 25
Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
Style/SymbolArray:
  Exclude:
     - spec/templates/*
